### ISSUE TITLE
Enable EC2 auto recovery

### ISSUE THREAD

**Issue by hjacobs** [zalando/planb-cassandra#1]
The `create-cluster.py` script needs to add a CloudWatch alarm for EC2 auto recovery, see https://aws.amazon.com/blogs/aws/new-auto-recovery-for-amazon-ec2/

**Comment by a1exsh** [comment]
see https://github.com/zalando/planb-cassandra/commit/a0bd875e296000f41a1fb5bcf41ffe5023ad0d5a

**Comment by hjacobs** [comment]
Let's test whether this really works...
