### ISSUE TITLE
Enable GC logging

### ISSUE THREAD

**Issue by a1exsh** [zalando/planb-cassandra#111]
For some reason we don't see the GC statistics in the cassandra log files anymore.

**Comment by a1exsh** [comment]
There cassandra.yaml option called `gc_warn_threshold_in_ms` since version 2.1 and since version 2.2 there is a separate `gc_log_threshold_in_ms` which we could set.

**Comment by slitsche** [comment]
We should solve #112 beforehand.

**Comment by a1exsh** [comment]
Currently we have `PrintGC[Details]` enabled, but the default configuration from Cassandra packages tries to send the GC logs to `/usr/share/cassandra/logs/gc.log` which does not exists.  We want to log to standard output instead.  For that we need to disable `-Xloggc` option.
