### ISSUE TITLE
The generated admin password should be printed to the console

### ISSUE THREAD

**Issue by hjacobs** [zalando/planb-cassandra#15]
We should have a last informative message to tell the user on how to connect to the Cassandra cluster (user "cassandra" and the admin password).

Right now I had to get the password from the user data --- this was no problem as I knew how to do that :smirk:

**Comment by a1exsh** [comment]
It's in the readme. Where do you think such a message would be appropriate?

**Comment by hjacobs** [comment]
I would expect a nice final message printed to the console containing the admin username & password and instructions such as:

* now create a new Cassandra user by doing `cqlsh` on ...
* change the Security Group xyz to allow access from your application
* change the Security Group xyz to allow Jolokia access from your monitoring tool

**Comment by a1exsh** [comment]
That sounds reasonable, I'll add something along those lines.

**Comment by a1exsh** [comment]
Added in https://github.com/zalando/planb-cassandra/commit/72e5c92a3a292bef2285db8dd61db6d347ed145f
