### ISSUE TITLE
Collect enhanced CloudWatch metrics for monitoring

### ISSUE THREAD

**Issue by a1exsh** [zalando/planb-cassandra#16]
Should be a simple Taupage config change + something to enable the IAM policy.

**Comment by hjacobs** [comment]
I'm not sure if we need this --- Prometheus Node Exporter (port 9100) does a pretty good job and provides more details :smirk:

**Comment by a1exsh** [comment]
Alright, lesson learned -- read docs more carefully ;-)

**Comment by hjacobs** [comment]
@a1exsh :+1: BTW: there is another reason not to use CloudWatch "too" much: you quickly run into stupid AWS API call rate limits with it (calls from ZMON), so it does not scale.. :smirk:
