### ISSUE TITLE
Authnz is broken with new cluster using DC suffix

### ISSUE THREAD

**Issue by lmineiro** [zalando/planb-cassandra#167]
When creating a new cluster using the DC suffix option, the replication settings are not properly applied to the system_auth keyspace: https://github.com/zalando/planb-cassandra/blob/57fd5fee1172fa0e29a8a892783e6c4237e74f87/Dockerfiles/Cassandra-3/planb-cassandra.sh#L126

**Comment by a1exsh** [comment]
We have removed the automated ALTER KEYSPACE from the script, because it was causing serious trouble when using multiple virtual DCs, in favor of providing instructions for the deployer to do this manually exactly once: right after creating the cluster.
