### ISSUE TITLE
Move cassandra data/log directories outside the Docker container

### ISSUE THREAD

**Issue by a1exsh** [zalando/planb-cassandra#18]
This will help in updating cassandra binaries and keeping the data intact.

**Comment by a1exsh** [comment]
My current idea is to go with `docker -v /host-dir:/container-dir`, which can be achieved by specifying `mounts:` section in Taupage user data.  Two problems with that currently:

1. Taupage will not create the host directory (nor will Docker, this was deprecated in version 1.9).
2. The directory must be created with appropriate permissions (writable by the `application` user).

@hjacobs Should I open a PR with Taupage?

**Comment by hjacobs** [comment]
What about using just "VOLUME" in Dockerfile? Did you try/consider it?

**Comment by a1exsh** [comment]
It doesn't work, or could not figure it out given the available docs.

**Comment by a1exsh** [comment]
After thinking more about this I guess we need a separate EBS volume for the data and a smallish one for the Taupage AMI.  @hjacobs I think you were also suggesting that, correct?

**Comment by hjacobs** [comment]
@a1exsh yes, let's use a dedicated EBS volume for data.

**Comment by a1exsh** [comment]
We are tracking this in the PR: #19
