### ISSUE TITLE
Do not log inside Docker container to Cassandra system.log

### ISSUE THREAD

**Issue by hjacobs** [zalando/planb-cassandra#2]
`/var/log/cassandra/system.log` should not be present/written, everything goes to STDOUT anyway.

**Comment by hjacobs** [comment]
This issue is quite important for production-readiness to mitigate "out of diskspace" problems.

**Comment by a1exsh** [comment]
Fixed with: https://github.com/zalando/planb-cassandra/commit/430297e42b796c65abaca610afe6694ff5ff88d8
