### ISSUE TITLE
Support rolling updates of Docker image

### ISSUE THREAD

**Issue by a1exsh** [zalando/planb-cassandra#24]
Implement a command in cluster management script that will act on the specified cluster nodes one by one, stopping the old docker container cleanly, stopping the EC2 instance, updating instance user data to use the newer docker image, then starting the EC2 instance back.

Ideally, no state should be stored locally and the script should be able to continue after failure/bug/exception by assessing the current state of the EC2 instances.  So that an incomplete update could be easily picked up by another operator, by running the update procedure again from a different local system.

**Comment by LappleApple** [comment]
Hey @a1exsh, can we close this issue? It dates back to April 2016. 

Or, we could add a "Help Wanted" label.

**Comment by a1exsh** [comment]
We are working on these right this moment.  Not all is lost. ;-)

**Comment by slitsche** [comment]
#109 solves this.
