### ISSUE TITLE
Support rolling updates of Taupage AMI

### ISSUE THREAD

**Issue by a1exsh** [zalando/planb-cassandra#25]
See #24 for design.  This variant could work by stopping EC2, detach rootfs, creating a new volume from desired Taupage snapshot, attaching the rootfs, then starting the EC2 back again.

**Comment by Jan-M** [comment]
This should also include modifying the instance type.

It seems we need a comfortable option of starting small and growing bigger in node size and number of nodes.

**Comment by slitsche** [comment]
#109 Solves most of it. Change instance type is not yet implemented. but the infrastucture is there.
