### ISSUE TITLE
Building the docker file with Ubuntu 16.04 base image doesn't work

### ISSUE THREAD

**Issue by MALPI** [zalando/planb-cassandra#26]
Since #20 isn't solved yet I wanted to build my own docker Image with the newest AMI 'registry.opensource.zalan.do/stups/openjdk:8u77-b03-1-20' unfortunately this leads to the following Error:

`Step 1 : FROM registry.opensource.zalan.do/stups/openjdk:8u77-b03-1-20
 ---> c4d654ea74a2
Step 2 : MAINTAINER Zalando SE
 ---> Using cache
 ---> 1a5b5eb8aa6e
Step 3 : EXPOSE 7001 8778 9042
 ---> Using cache
 ---> ca2ed60f8479
Step 4 : ENV CASSIE_VERSION 2.1.13
 ---> Using cache
 ---> 60aab73901bd
Step 5 : ENV DEBIAN_FRONTEND noninteractive
 ---> Using cache
 ---> 03359451d305
Step 6 : RUN echo "deb http://debian.datastax.com/community stable main" | tee -a /etc/apt/sources.list.d/datastax.community.list
 ---> Using cache
 ---> 691101a5a455
Step 7 : RUN curl -sL https://debian.datastax.com/debian/repo_key | apt-key add -
 ---> Using cache
 ---> 80d0ccb4ab0b
Step 8 : RUN apt-get -y update && apt-get -y -o Dpkg::Options::='--force-confold' --fix-missing dist-upgrade
 ---> Using cache
 ---> d1d85c34ba39
Step 9 : RUN apt-get -y install python-support cassandra=$CASSIE_VERSION cassandra-tools=$CASSIE_VERSION sysstat && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
 ---> Running in fd6532f0ee62
Reading package lists...
Building dependency tree...
Package python-support is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
`
Therefore I tried to build with the original file in order to identify if the issue already existed beforehands, what leads to the following error:

`Removing intermediate container be8ea8cba540
Step 22 : COPY scm-source.json /
lstat scm-source.json: no such file or directory
`

**Comment by hjacobs** [comment]
@MALPI yes, you need to run `scm-source` before building Docker, see http://docs.stups.io/en/latest/user-guide/application-development.html#scm-source-json

**Comment by MALPI** [comment]
@hjacobs ok, I didn't know that. Nevertheless it's not possible to build it with the new JDK Image.

**Comment by hjacobs** [comment]
@MALPI yes, the Cassandra Debian packages requires the "python-support" package which no longer exists on Ubuntu 16.04 (http://stackoverflow.com/questions/36880886/error-while-installing-cassandra)

**Comment by a1exsh** [comment]
This is no longer the case apparently.  I can build a docker image with the most recent openjdk base image without a problem (see #31).
