### ISSUE TITLE
Contact points discovery

### ISSUE THREAD

**Issue by a1exsh** [zalando/planb-cassandra#29]
Probably using DNS records.

**Comment by hjacobs** [comment]
We should (?) use the standardized way of SRV records: https://en.wikipedia.org/wiki/SRV_record

The targets could point to the EC2 Elastic IP DNS names.

**Comment by a1exsh** [comment]
The SRV records approach seems to work, however we need to decide on the naming.  Looks like we need a name per region, e.g: `_planb-cassandra-eu-central-1._tcp.<hosted.zone>.` and `_planb-cassandra-eu-west-1._tcp.<hosted.zone>.`.
