### ISSUE TITLE
Use up to 3 seed nodes per region

### ISSUE THREAD

**Issue by hjacobs** [zalando/planb-cassandra#3]
We should use up to 3 seed nodes per region, not only one.

**Comment by hjacobs** [comment]
@lmineiro recommends this :smile:

**Comment by a1exsh** [comment]
I will take this one :)

**Comment by a1exsh** [comment]
Please see: https://github.com/zalando/planb-cassandra/commit/8a68add62cea591d411262e40499c082d8a132b0

**Comment by hjacobs** [comment]
:+1: works
