### ISSUE TITLE
Update Documentation for replication factor of system keyspace

### ISSUE THREAD

**Issue by MALPI** [zalando/planb-cassandra#33]
Hey,

Since we are using Password authentication in planB-Cassandra, the replication factor of the system keyspace should be increased according to this [documentation](https://docs.datastax.com/en/cql/3.1/cql/cql_using/update_ks_rf_t.html). Which makes totally sense..

Nevertheless to make it more explicit, I think it's worth to mention it in the README.md, or even better to do it during the setup of the cluster.

**Comment by a1exsh** [comment]
It is done during setup of the cluster more or less, for details see at the
bottom of Docker entry point script.

**Comment by a1exsh** [comment]
See: https://github.com/zalando/planb-cassandra/blob/master/planb-cassandra.sh#L88

Btw, this is about `system_auth` keyspace, not `system`--the latter one gets replicated automatically to all nodes regardless of the settings, I believe.
