### ISSUE TITLE
Add option(s) to configure EBS

### ISSUE THREAD

**Issue by hjacobs** [zalando/planb-cassandra#4]
We don't need it for our current project, but in general we should support a (few) options to configure EBS, e.g. size.

**Comment by slitsche** [comment]
We should not use the standard EBS type, but gp2.

**Comment by a1exsh** [comment]
We probably also want to be able to specify EBS-optimized instances: http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSOptimized.html

Though, this parameter can be changed after starting the instance.
