### ISSUE TITLE
Provide a docker image for Cassandra 3

### ISSUE THREAD

**Issue by smourapina** [zalando/planb-cassandra#48]
We need some features from Cassandra 3. It would be good if you could provide a docker image for this version of Cassandra, as your current ones are for 2.x.

**Comment by a1exsh** [comment]
Great :-)  I envision the following steps to achieve this:

* change Cassandra version variable in the Dockerfile to a desired version
* see if the docker image can still be built (probably review that workaround for python version, if it needs to be adjusted or removed)
* pull in the `cassandra-env.sh` and `cassandra.yaml` (our config template is based on slighlty tuned default config) files from the version 3.x, check how are they different from the old ones and apply relevant changes.  In the env file I think we only enable local JMX for Jolokia.
* see if the docker image builds and Cassandra can bootstrap itself with one node on your laptop

That should be it.

**Comment by smourapina** [comment]
@a1exsh Following your steps I have successfully deployed Cassandra 3.0.8 to AWS. Please let me know how to proceed in opening a PR with my changes in order to support this in your project.

**Comment by a1exsh** [comment]
@smourapina I think we should create two branches: 2.1 and 3.0.  Then you could simply open the PR against branch 3.0.

**Comment by a1exsh** [comment]
Closing this as #56 got merged.
