### ISSUE TITLE
Scale up procedure might be risky

### ISSUE THREAD

**Issue by a1exsh** [zalando/planb-cassandra#93]
We've seen that occasionally when attaching an EBS volume to a running instance as documented in the "Scale up" manual, it might lead to filesystem being wiped out due to kernel errors when trying to mount it:
```
Nov 23 13:56:52 ip-172-31-128-12 kernel: [   37.769527] blkfront: xvdf: barrier or flush: disabled; persistent grants: enabled; indirect descriptors: enabled;
Nov 23 13:56:52 ip-172-31-128-12 kernel: [   37.772899]  xvdf: unknown partition table
```

The procedure needs to be improved, probably to only attach the volume when the instance isn't running.

**Comment by a1exsh** [comment]
The problem seems to be that `wait_for_device` by default only waits for up to 15 seconds.  If you are unlucky to attach the volume just after mount failure, the next step is to format it.

**Comment by slitsche** [comment]
#97 solves this.
